# Generated by Django 4.2.5 on 2023-10-10 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250, null=True)),
                ('category_description', models.CharField(max_length=250, null=True)),
                ('category_code', models.CharField(max_length=250, unique=True)),
                ('slug', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=64, null=True, verbose_name='Customer Name')),
                ('contact_number', models.CharField(max_length=20, null=True)),
                ('customer_city', models.CharField(max_length=200, null=True)),
                ('customer_code', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=250, null=True)),
                ('product_description', models.CharField(max_length=250, null=True)),
                ('defaul_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='onstock', max_length=100)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_type', models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('nos', 'Number'), ('gram', 'Gram'), ('litre', 'Litre')], max_length=20, null=True)),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bcoadmin.category')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.CharField(max_length=250, null=True)),
                ('category_code', models.CharField(max_length=250, unique=True)),
                ('slug', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=250, null=True)),
                ('supplier_phone', models.CharField(max_length=250, null=True)),
                ('supplier_city', models.CharField(max_length=250, null=True)),
                ('supplier_code', models.CharField(max_length=250, unique=True)),
                ('added_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='StockReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_quantity', models.IntegerField(default=1)),
                ('return_reason', models.TextField()),
                ('return_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bcoadmin.customer')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bcoadmin.products')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bcoadmin.suppliers')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_out', models.IntegerField(default=1)),
                ('stockout_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bcoadmin.customer')),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bcoadmin.products')),
                ('stock_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bcoadmin.stockreturn')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_purchased', models.IntegerField(default=1)),
                ('stockin_date_and_time', models.DateTimeField(auto_now_add=True)),
                ('product_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bcoadmin.products')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bcoadmin.suppliers')),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='sub_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bcoadmin.subcategory'),
        ),
        migrations.AddField(
            model_name='products',
            name='vendor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bcoadmin.suppliers'),
        ),
    ]
