# Generated by Django 4.2.5 on 2023-10-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcoadmin', '0002_alter_products_quantity_alter_products_unit_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='min_quantity',
            field=models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
        ),
    ]
