# Generated by Django 4.2.5 on 2023-10-12 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcoadmin', '0005_category_category_image_products_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='slug',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
