# Generated by Django 4.2.5 on 2023-10-12 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcoadmin', '0006_alter_subcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='bcoadmin.category'),
        ),
    ]
