# Generated by Django 4.2.5 on 2023-10-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bcoadmin', '0007_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_code',
            field=models.CharField(default='ML009', max_length=250),
        ),
    ]
