# Generated by Django 4.2.5 on 2023-10-15 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bcoadmin', '0011_alter_category_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='sub_category',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='bcoadmin.subcategory'),
        ),
    ]
